function Ex1_3_1_DoisSegm

clc
close all

% =========================================================
% Figura
% =========================================================

fig = figure( ...
    'Name','Cinematica Interativa', ...
    'Position',[100 100 700 600]);

ax = axes( ...
    'Parent',fig, ...
    'Position',[0.10 0.30 0.85 0.65]);

grid(ax,'on')
axis(ax,'equal')
axis(ax,[-15 15 -15 15])

xlabel(ax,'x [cm]')
ylabel(ax,'y [cm]')

title(ax,'Cinematica Direta Interativa')

hold(ax,'on')

% =========================================================
% Slider Theta1
% =========================================================

uicontrol( ...
    'Style','text', ...
    'Position',[40 160 120 20], ...
    'String','Theta1 [graus]');

s1 = uicontrol( ...
    'Style','slider', ...
    'Min',-180, ...
    'Max',180, ...
    'Value',30, ...
    'Position',[40 140 220 20], ...
    'Callback',@updatePlot);

% =========================================================
% Slider Theta2
% =========================================================

uicontrol( ...
    'Style','text', ...
    'Position',[40 110 120 20], ...
    'String','Theta2 [graus]');

s2 = uicontrol( ...
    'Style','slider', ...
    'Min',-180, ...
    'Max',180, ...
    'Value',20, ...
    'Position',[40 90 220 20], ...
    'Callback',@updatePlot);

% =========================================================
% Slider L1
% =========================================================

uicontrol( ...
    'Style','text', ...
    'Position',[380 160 120 20], ...
    'String','L1 [cm]');

s3 = uicontrol( ...
    'Style','slider', ...
    'Min',1, ...
    'Max',10, ...
    'Value',5, ...
    'Position',[380 140 220 20], ...
    'Callback',@updatePlot);

% =========================================================
% Slider L2
% =========================================================

uicontrol( ...
    'Style','text', ...
    'Position',[380 110 120 20], ...
    'String','L2 [cm]');

s4 = uicontrol( ...
    'Style','slider', ...
    'Min',1, ...
    'Max',10, ...
    'Value',5, ...
    'Position',[380 90 220 20], ...
    'Callback',@updatePlot);

% =========================================================
% Primeira atualizacao
% =========================================================

updatePlot()

% =========================================================
% Funcao interna
% =========================================================

    function updatePlot(~,~)

        theta1 = get(s1,'Value');
        theta2 = get(s2,'Value');

        L1 = get(s3,'Value');
        L2 = get(s4,'Value');

        t1 = deg2rad(theta1);
        t2 = deg2rad(theta2);

        % Junta intermediaria
        x1 = L1*cos(t1);
        y1 = L1*sin(t1);

        % Extremidade
        x2 = x1 + L2*cos(t1+t2);
        y2 = y1 + L2*sin(t1+t2);

        cla(ax)

        grid(ax,'on')
        axis(ax,'equal')
        axis(ax,[-15 15 -15 15])

        hold(ax,'on')

        % Segmento 1
        plot(ax,[0 x1],[0 y1], ...
            '-o', ...
            'LineWidth',4);

        % Segmento 2
        plot(ax,[x1 x2],[y1 y2], ...
            '-o', ...
            'LineWidth',4);

        % Pé
        plot(ax,x2,y2, ...
            'ro', ...
            'MarkerSize',12, ...
            'MarkerFaceColor','r');

        title(ax, ...
            sprintf([ ...
            'Theta1 = %.1f°   |   Theta2 = %.1f°\n' ...
            'Pe = (%.2f , %.2f) cm'], ...
            theta1,theta2,x2,y2));

    end

end